version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # For hot-reloading on Windows
    depends_on:
      - backend
    networks:
      - dashboard-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules # Exclude node_modules from being overwritten by the volume
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - dashboard-net

  db:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env
    networks:
      - dashboard-net

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - dashboard-net

networks:
  dashboard-net:
    driver: bridge

volumes:
  postgres_data:
